---
title: "Equation 1"
author: 'Parv Joshi, ID: 112169570'
date: "4/19/2021"
output: word_document
---

```{r}
setwd("C:/Users/Lenovo/Desktop/Spring 2021/ECO 487 459")

library(tidyverse)
library(AER)
library(sandwich)
library(lmtest)
library(car)
library(MASS)

data = read.csv("data.csv", sep = ",", header = T)
attach(data)
```


```{r}
# Equation 1 Final Model

Model1 = lm(CASES ~ ., data = data)
summary(Model1)$adj.r.squared

Model1 = lm(I(log(CASES)) ~ ., data = data)
summary(Model1)$adj.r.squared

Model1 = lm(CASES ~ (.)^2, data = data)
summary(Model1)$adj.r.squared

Model1 = lm(I(log(CASES)) ~ (.)^2, data = data)
summary(Model1)$adj.r.squared

Model1 = lm(CASES ~ (.)^2 + I(SANITATION^2)+ I(SANITATION^3) + I(log(SL)) + I(WATER^2) + I(WATER^3), data = data)
summary(Model1)$adj.r.squared

Model1 = lm(I(log(CASES)) ~ (.)^2 + I(SANITATION^2)+ I(SANITATION^3) + I(log(SL)) + I(WATER^2) + I(WATER^3), data = data)
summary(Model1)$adj.r.squared

# This One
Model1 = lm(CASES ~ (HCI + HAQI + HYGIENE + MEAT + PD + SANITATION + I(SANITATION^2) + I(SANITATION^3) + I(log(SL)) + WATER + I(WATER^2) + I(WATER^3) + MEAT*PD + MEAT*HAQI + PD*HYGIENE + PD*SANITATION + PD*HAQI + WATER*SL), data = data)
summary(Model1)$adj.r.squared

Model1 = lm(I(log(CASES)) ~ (HCI + HAQI + HYGIENE + MEAT + PD + SANITATION + I(SANITATION^2) + I(SANITATION^3) + I(log(SL)) + WATER + I(WATER^2) + I(WATER^3) + MEAT*PD + MEAT*HAQI + PD*HYGIENE + PD*SANITATION + PD*HAQI + WATER*SL), data = data)
summary(Model1)$adj.r.squared

Model1 = lm(CASES ~ HCI + HAQI + HYGIENE + MEAT + PD + SANITATION + I(SANITATION^2) + I(SANITATION^3) + I(log(SL)) + WATER + I(WATER^2) + I(WATER^3), data = data)
summary(Model1)$adj.r.squared

Model1 = lm(I(log(CASES)) ~ HCI + HAQI + HYGIENE + MEAT + PD + SANITATION + I(SANITATION^2) + I(SANITATION^3) + I(log(SL)) + WATER + I(WATER^2) + I(WATER^3), data = data)
summary(Model1)$adj.r.squared

# --------------------------

Model = lm(CASES ~ (HCI + HAQI + HYGIENE + MEAT + PD + SANITATION + I(SANITATION^2) + I(SANITATION^3) + I(log(SL)) + WATER + I(WATER^2) + I(WATER^3) + MEAT*PD + MEAT*HAQI + PD*HYGIENE + PD*SANITATION + PD*HAQI + WATER*SL), data = data)

bc = boxcox(Model, lambda = seq(-3,3))
lam = bc$x[which(bc$y==max(bc$y))]
lam

Model_bc = lm(I(CASES^lam) ~ (HCI + HAQI + HYGIENE + MEAT + PD + SANITATION + I(SANITATION^2) + I(SANITATION^3) + I(log(SL)) + WATER + I(WATER^2) + I(WATER^3) + MEAT*PD + MEAT*HAQI + PD*HYGIENE + PD*SANITATION + PD*HAQI + WATER*SL), data = data)
summary(Model_bc)$adj.r.squared
# The boxcox transformation worsens our model's fit. Hence, we must not use it.

FinalModel1 = lm(CASES ~ (HCI + HAQI + HYGIENE + MEAT + PD + SANITATION + I(SANITATION^2) + I(SANITATION^3) + I(log(SL)) + WATER + I(WATER^2) + I(WATER^3) + MEAT*PD + MEAT*HAQI + PD*HYGIENE + PD*SANITATION + PD*HAQI + WATER*SL), data = data)
summary(FinalModel1)
hetero_FinalModel1 = coeftest(FinalModel1, vcov = vcovHC(FinalModel1, "HC1"))
hetero_FinalModel1
```

